CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(120) NOT NULL,
    parent_id BIGINT REFERENCES categories(id),
    CONSTRAINT category_not_own_parent CHECK (parent_id IS NULL OR parent_id <> id)
);

-- Reference taxonomy only. No user accounts, personal data or policy assumptions.
INSERT INTO categories (code, name) VALUES
    ('TEXTBOOKS', 'Textbooks and study materials'),
    ('APPLIANCES', 'Dorm appliances'),
    ('FURNITURE', 'Small furniture');
