-- Shared storage foundation, requirements v1.1. No business endpoints/jobs are enabled.
-- Application transaction obligations and deferred policy: docs/architecture/shared-domain-schema.md.
-- UUIDs are generated by the application. V1 category IDs remain BIGINT.
CREATE TABLE members (
    id UUID PRIMARY KEY,
    email VARCHAR(254) NOT NULL CHECK (email = lower(btrim(email))),
    student_id VARCHAR(80) UNIQUE, -- nullable for unresolved identity exceptions; never the PK
    display_name VARCHAR(160) NOT NULL,
    password_hash TEXT NOT NULL,
    university VARCHAR(160), major VARCHAR(160), cohort VARCHAR(80), campus VARCHAR(160),
    phone VARCHAR(40), private_address TEXT,
    graduated BOOLEAN NOT NULL DEFAULT FALSE,
    email_verified_at TIMESTAMPTZ,
    identity_approved_at TIMESTAMPTZ,
    identity_approved_by UUID REFERENCES members(id),
    activated_at TIMESTAMPTZ,
    reputation INTEGER NOT NULL DEFAULT 0,
    version BIGINT NOT NULL DEFAULT 0 CHECK (version >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT member_email_unique UNIQUE (email),
    CONSTRAINT activation_requires_both_checks CHECK (activated_at IS NULL OR
        (email_verified_at IS NOT NULL AND identity_approved_at IS NOT NULL AND identity_approved_by IS NOT NULL))
);
CREATE TABLE member_roles (
    member_id UUID NOT NULL REFERENCES members(id),
    role VARCHAR(24) NOT NULL CHECK (role IN ('MEMBER', 'MODERATOR', 'ADMIN')),
    PRIMARY KEY (member_id, role)
);
CREATE TABLE media_assets (
    id UUID PRIMARY KEY,
    owner_id UUID NOT NULL REFERENCES members(id),
    purpose VARCHAR(24) NOT NULL CHECK (purpose IN ('LISTING', 'STUDENT_CARD', 'HANDOVER', 'REPORT')),
    storage_key UUID NOT NULL UNIQUE, -- server-generated key; never a client path/URL
    content_type VARCHAR(120) NOT NULL,
    byte_size BIGINT NOT NULL CHECK (byte_size > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (id, owner_id, purpose)
);
CREATE TABLE inventory_items (
    id UUID PRIMARY KEY,
    seller_id UUID NOT NULL REFERENCES members(id),
    name VARCHAR(200) NOT NULL,
    condition_description TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (id, seller_id)
);
CREATE TABLE listings (
    id UUID PRIMARY KEY,
    seller_id UUID NOT NULL REFERENCES members(id),
    publication_state VARCHAR(24) NOT NULL DEFAULT 'DRAFT'
        CHECK (publication_state IN ('DRAFT', 'PUBLISHED', 'HIDDEN', 'WITHDRAWN', 'ARCHIVED')),
    published_revision_id UUID,
    version BIGINT NOT NULL DEFAULT 0 CHECK (version >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (id, seller_id),
    CHECK (publication_state <> 'PUBLISHED' OR published_revision_id IS NOT NULL)
);
CREATE TABLE listing_revisions (
    id UUID PRIMARY KEY,
    listing_id UUID NOT NULL,
    seller_id UUID NOT NULL,
    revision_number INTEGER NOT NULL CHECK (revision_number > 0),
    review_state VARCHAR(16) NOT NULL DEFAULT 'DRAFT'
        CHECK (review_state IN ('DRAFT', 'PENDING', 'APPROVED', 'REJECTED')),
    title VARCHAR(200) NOT NULL,
    description TEXT NOT NULL,
    category_id BIGINT NOT NULL REFERENCES categories(id),
    offer_type VARCHAR(16) NOT NULL CHECK (offer_type IN ('SALE', 'GIVEAWAY')),
    price_vnd BIGINT NOT NULL CHECK (price_vnd BETWEEN 0 AND 9007199254740991),
    area_label VARCHAR(200) NOT NULL, -- coarse public location, not private address/GPS
    author VARCHAR(200), publisher VARCHAR(200), course_code VARCHAR(80), lecturer VARCHAR(200),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (listing_id, revision_number),
    UNIQUE (id, listing_id, seller_id),
    UNIQUE (id, seller_id),
    FOREIGN KEY (listing_id, seller_id) REFERENCES listings(id, seller_id),
    CHECK (offer_type <> 'GIVEAWAY' OR price_vnd = 0)
);
ALTER TABLE listings ADD CONSTRAINT published_revision_belongs_to_listing
    FOREIGN KEY (published_revision_id, id, seller_id) REFERENCES listing_revisions(id, listing_id, seller_id);
CREATE TABLE listing_revision_items (
    revision_id UUID NOT NULL,
    item_id UUID NOT NULL,
    seller_id UUID NOT NULL,
    PRIMARY KEY (revision_id, item_id),
    FOREIGN KEY (revision_id, seller_id) REFERENCES listing_revisions(id, seller_id),
    FOREIGN KEY (item_id, seller_id) REFERENCES inventory_items(id, seller_id)
);
CREATE TABLE listing_revision_photos (
    revision_id UUID NOT NULL,
    media_id UUID NOT NULL,
    seller_id UUID NOT NULL,
    purpose VARCHAR(24) NOT NULL DEFAULT 'LISTING' CHECK (purpose = 'LISTING'),
    position SMALLINT NOT NULL CHECK (position BETWEEN 1 AND 5),
    PRIMARY KEY (revision_id, position),
    UNIQUE (revision_id, media_id),
    FOREIGN KEY (revision_id, seller_id) REFERENCES listing_revisions(id, seller_id),
    FOREIGN KEY (media_id, seller_id, purpose) REFERENCES media_assets(id, owner_id, purpose)
);
CREATE TABLE listing_reviews (
    id UUID PRIMARY KEY,
    revision_id UUID NOT NULL REFERENCES listing_revisions(id),
    reviewer_id UUID NOT NULL REFERENCES members(id),
    verdict VARCHAR(16) NOT NULL CHECK (verdict IN ('APPROVED', 'REJECTED')),
    reason TEXT NOT NULL CHECK (length(btrim(reason)) > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE listing_events (
    id UUID PRIMARY KEY,
    listing_id UUID NOT NULL REFERENCES listings(id),
    actor_id UUID NOT NULL REFERENCES members(id),
    action VARCHAR(80) NOT NULL,
    reason TEXT NOT NULL CHECK (length(btrim(reason)) > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE conversations (
    id UUID PRIMARY KEY,
    listing_id UUID NOT NULL,
    seller_id UUID NOT NULL,
    buyer_id UUID NOT NULL REFERENCES members(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (listing_id, seller_id) REFERENCES listings(id, seller_id),
    CHECK (buyer_id <> seller_id),
    UNIQUE (listing_id, buyer_id),
    UNIQUE (id, listing_id, seller_id, buyer_id)
);
CREATE TABLE messages (
    id UUID PRIMARY KEY,
    conversation_id UUID NOT NULL REFERENCES conversations(id),
    sender_id UUID NOT NULL REFERENCES members(id), -- service checks participant membership
    body TEXT NOT NULL CHECK (length(btrim(body)) > 0 AND length(body) <= 4000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE price_proposals (
    id UUID PRIMARY KEY,
    conversation_id UUID NOT NULL,
    listing_id UUID NOT NULL,
    seller_id UUID NOT NULL,
    buyer_id UUID NOT NULL,
    revision_id UUID NOT NULL,
    amount_vnd BIGINT NOT NULL CHECK (amount_vnd BETWEEN 0 AND 9007199254740991),
    state VARCHAR(16) NOT NULL DEFAULT 'PENDING' CHECK (state IN ('PENDING', 'ACCEPTED', 'REJECTED')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (conversation_id, listing_id, seller_id, buyer_id)
        REFERENCES conversations(id, listing_id, seller_id, buyer_id),
    FOREIGN KEY (revision_id, listing_id, seller_id) REFERENCES listing_revisions(id, listing_id, seller_id),
    UNIQUE (id, listing_id, seller_id, buyer_id)
);
CREATE TABLE reservations (
    id UUID PRIMARY KEY,
    listing_id UUID NOT NULL,
    seller_id UUID NOT NULL,
    buyer_id UUID NOT NULL REFERENCES members(id),
    revision_id UUID NOT NULL,
    proposal_id UUID,
    state VARCHAR(24) NOT NULL DEFAULT 'REQUESTED'
        CHECK (state IN ('REQUESTED', 'ACCEPTED', 'REJECTED', 'CANCELLED', 'COMPLETED')),
    agreed_price_vnd BIGINT CHECK (agreed_price_vnd BETWEEN 0 AND 9007199254740991),
    listing_snapshot JSONB CHECK (jsonb_typeof(listing_snapshot) = 'object'),
    accepted_at TIMESTAMPTZ,
    cancelled_by UUID REFERENCES members(id), cancellation_reason TEXT,
    rejected_by UUID REFERENCES members(id), rejection_reason TEXT,
    version BIGINT NOT NULL DEFAULT 0 CHECK (version >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (listing_id, seller_id) REFERENCES listings(id, seller_id),
    FOREIGN KEY (revision_id, listing_id, seller_id) REFERENCES listing_revisions(id, listing_id, seller_id),
    FOREIGN KEY (proposal_id, listing_id, seller_id, buyer_id) REFERENCES price_proposals(id, listing_id, seller_id, buyer_id),
    CHECK (buyer_id <> seller_id),
    CHECK (state NOT IN ('ACCEPTED', 'COMPLETED') OR
        (accepted_at IS NOT NULL AND agreed_price_vnd IS NOT NULL AND listing_snapshot IS NOT NULL)),
    CHECK (state <> 'CANCELLED' OR (cancelled_by IS NOT NULL AND length(btrim(cancellation_reason)) > 0 AND cancellation_reason IS NOT NULL)),
    CHECK (state <> 'REJECTED' OR (rejected_by IS NOT NULL AND rejection_reason IS NOT NULL AND length(btrim(rejection_reason)) > 0)),
    UNIQUE (id, seller_id),
    UNIQUE (id, seller_id, buyer_id)
);
-- COMPLETED remains occupied: one listing can produce at most one completed trade.
CREATE UNIQUE INDEX one_accepted_or_completed_reservation_per_listing ON reservations(listing_id)
    WHERE state IN ('ACCEPTED', 'COMPLETED');
CREATE TABLE reservation_items (
    reservation_id UUID NOT NULL,
    item_id UUID NOT NULL,
    seller_id UUID NOT NULL,
    item_name_snapshot VARCHAR(200) NOT NULL,
    condition_snapshot TEXT NOT NULL,
    allocation_state VARCHAR(16) NOT NULL CHECK (allocation_state IN ('HELD', 'SOLD', 'RELEASED')),
    PRIMARY KEY (reservation_id, item_id),
    FOREIGN KEY (reservation_id, seller_id) REFERENCES reservations(id, seller_id),
    FOREIGN KEY (item_id, seller_id) REFERENCES inventory_items(id, seller_id)
);
-- Retain SOLD rows permanently. Availability is derived from this table, not a second flag.
CREATE UNIQUE INDEX one_hold_or_sale_per_physical_item ON reservation_items(item_id)
    WHERE allocation_state IN ('HELD', 'SOLD');

-- Preserve agreed history even if a future entity mapper accidentally writes every field.
CREATE FUNCTION protect_reservation_history() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'Reservation history cannot be deleted' USING ERRCODE = '23514';
    END IF;
    IF OLD.accepted_at IS NOT NULL AND
       ROW(NEW.listing_id, NEW.revision_id, NEW.seller_id, NEW.buyer_id, NEW.proposal_id,
           NEW.agreed_price_vnd, NEW.listing_snapshot, NEW.accepted_at)
       IS DISTINCT FROM
       ROW(OLD.listing_id, OLD.revision_id, OLD.seller_id, OLD.buyer_id, OLD.proposal_id,
           OLD.agreed_price_vnd, OLD.listing_snapshot, OLD.accepted_at) THEN
        RAISE EXCEPTION 'Accepted reservation snapshot is immutable' USING ERRCODE = '23514';
    END IF;
    IF OLD.state IN ('COMPLETED', 'CANCELLED', 'REJECTED') AND NEW.state <> OLD.state THEN
        RAISE EXCEPTION 'Terminal reservation cannot reopen' USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER reservation_history_guard BEFORE UPDATE OR DELETE ON reservations
    FOR EACH ROW EXECUTE FUNCTION protect_reservation_history();

CREATE FUNCTION protect_allocation_history() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'Allocation history cannot be deleted; release held rows on cancellation' USING ERRCODE = '23514';
    END IF;
    IF ROW(NEW.reservation_id, NEW.item_id, NEW.seller_id, NEW.item_name_snapshot, NEW.condition_snapshot)
       IS DISTINCT FROM ROW(OLD.reservation_id, OLD.item_id, OLD.seller_id, OLD.item_name_snapshot, OLD.condition_snapshot) THEN
        RAISE EXCEPTION 'Allocation snapshot is immutable' USING ERRCODE = '23514';
    END IF;
    IF OLD.allocation_state IN ('SOLD', 'RELEASED') AND NEW.allocation_state <> OLD.allocation_state THEN
        RAISE EXCEPTION 'Terminal allocation cannot be reused' USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER allocation_history_guard BEFORE UPDATE OR DELETE ON reservation_items
    FOR EACH ROW EXECUTE FUNCTION protect_allocation_history();
CREATE TABLE appointments (
    reservation_id UUID PRIMARY KEY REFERENCES reservations(id),
    meeting_at TIMESTAMPTZ NOT NULL,
    place_description TEXT NOT NULL,
    updated_by UUID NOT NULL REFERENCES members(id),
    version BIGINT NOT NULL DEFAULT 0 CHECK (version >= 0)
);
CREATE TABLE trades (
    id UUID PRIMARY KEY,
    reservation_id UUID NOT NULL UNIQUE,
    seller_id UUID NOT NULL,
    buyer_id UUID NOT NULL,
    state VARCHAR(24) NOT NULL DEFAULT 'AWAITING_HANDOVER'
        CHECK (state IN ('AWAITING_HANDOVER', 'AWAITING_CONFIRMATION', 'ADMIN_REVIEW', 'COMPLETED', 'CANCELLED')),
    handover_reported_at TIMESTAMPTZ,
    review_due_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    rating_due_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0 CHECK (version >= 0),
    FOREIGN KEY (reservation_id, seller_id, buyer_id) REFERENCES reservations(id, seller_id, buyer_id),
    UNIQUE (id, seller_id),
    UNIQUE (id, buyer_id),
    UNIQUE (id, seller_id, buyer_id),
    CHECK ((handover_reported_at IS NULL AND review_due_at IS NULL) OR
        (handover_reported_at IS NOT NULL AND review_due_at IS NOT NULL AND review_due_at = handover_reported_at + interval '24 hours')),
    CHECK (state NOT IN ('AWAITING_CONFIRMATION', 'ADMIN_REVIEW', 'COMPLETED') OR handover_reported_at IS NOT NULL),
    CHECK ((state = 'COMPLETED' AND completed_at IS NOT NULL AND rating_due_at IS NOT NULL AND rating_due_at = completed_at + interval '360 hours') OR
        (state <> 'COMPLETED' AND completed_at IS NULL AND rating_due_at IS NULL))
);
CREATE TABLE handover_evidence (
    trade_id UUID NOT NULL,
    media_id UUID NOT NULL,
    seller_id UUID NOT NULL,
    purpose VARCHAR(24) NOT NULL DEFAULT 'HANDOVER' CHECK (purpose = 'HANDOVER'),
    PRIMARY KEY (trade_id, media_id),
    FOREIGN KEY (trade_id, seller_id) REFERENCES trades(id, seller_id),
    FOREIGN KEY (media_id, seller_id, purpose) REFERENCES media_assets(id, owner_id, purpose)
);
CREATE TABLE completion_challenges (
    id UUID PRIMARY KEY,
    trade_id UUID NOT NULL,
    buyer_id UUID NOT NULL,
    verifier TEXT NOT NULL, -- keyed verifier only, never plaintext or unsalted six-digit hash
    issued_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    failed_attempts SMALLINT NOT NULL DEFAULT 0 CHECK (failed_attempts BETWEEN 0 AND 5),
    invalidated_at TIMESTAMPTZ,
    consumed_at TIMESTAMPTZ,
    FOREIGN KEY (trade_id, buyer_id) REFERENCES trades(id, buyer_id),
    CHECK (expires_at = issued_at + interval '10 minutes')
);
CREATE UNIQUE INDEX one_current_completion_challenge ON completion_challenges(trade_id)
    WHERE invalidated_at IS NULL AND consumed_at IS NULL;
-- One row per trade chooses submission OR no-rating. Pending/rejected submissions still occupy the row.
CREATE TABLE rating_outcomes (
    trade_id UUID PRIMARY KEY,
    seller_id UUID NOT NULL,
    buyer_id UUID NOT NULL,
    outcome VARCHAR(16) NOT NULL CHECK (outcome IN ('SUBMITTED', 'NO_RATING')),
    stars SMALLINT,
    comment TEXT,
    review_state VARCHAR(16) CHECK (review_state IN ('PENDING', 'APPROVED', 'REJECTED', 'REMOVED')),
    created_at TIMESTAMPTZ NOT NULL,
    FOREIGN KEY (trade_id, seller_id, buyer_id) REFERENCES trades(id, seller_id, buyer_id),
    CHECK ((outcome = 'SUBMITTED' AND stars IS NOT NULL AND stars BETWEEN 1 AND 5 AND review_state IS NOT NULL) OR
        (outcome = 'NO_RATING' AND stars IS NULL AND comment IS NULL AND review_state IS NULL))
);
CREATE TABLE reports (
    id UUID PRIMARY KEY,
    reporter_id UUID NOT NULL REFERENCES members(id),
    reported_member_id UUID NOT NULL REFERENCES members(id),
    listing_id UUID REFERENCES listings(id),
    trade_id UUID REFERENCES trades(id),
    description TEXT NOT NULL CHECK (length(btrim(description)) > 0),
    state VARCHAR(24) NOT NULL DEFAULT 'SUBMITTED'
        CHECK (state IN ('SUBMITTED', 'UNDER_REVIEW', 'RESOLVED', 'DISMISSED')),
    duplicate_of UUID REFERENCES reports(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (duplicate_of IS NULL OR duplicate_of <> id),
    UNIQUE (id, reporter_id)
);
CREATE TABLE report_evidence (
    report_id UUID NOT NULL,
    media_id UUID NOT NULL,
    reporter_id UUID NOT NULL,
    purpose VARCHAR(24) NOT NULL DEFAULT 'REPORT' CHECK (purpose = 'REPORT'),
    PRIMARY KEY (report_id, media_id),
    FOREIGN KEY (report_id, reporter_id) REFERENCES reports(id, reporter_id),
    FOREIGN KEY (media_id, reporter_id, purpose) REFERENCES media_assets(id, owner_id, purpose)
);
CREATE TABLE moderation_decisions (
    id UUID PRIMARY KEY,
    report_id UUID REFERENCES reports(id),
    trade_id UUID REFERENCES trades(id),
    rating_trade_id UUID REFERENCES rating_outcomes(trade_id),
    actor_id UUID NOT NULL REFERENCES members(id),
    decision VARCHAR(80) NOT NULL, -- recorded reasoning, never an automatic sanction instruction
    reason TEXT NOT NULL CHECK (length(btrim(reason)) > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (num_nonnulls(report_id, trade_id, rating_trade_id) = 1)
);
CREATE TABLE reputation_entries (
    id UUID PRIMARY KEY,
    member_id UUID NOT NULL REFERENCES members(id),
    source_key VARCHAR(200) NOT NULL UNIQUE,
    kind VARCHAR(24) NOT NULL CHECK (kind IN ('ACTIVATION', 'RATING', 'NO_RATING', 'REVERSAL')),
    trade_id UUID REFERENCES rating_outcomes(trade_id),
    reverses_entry_id UUID UNIQUE REFERENCES reputation_entries(id),
    delta INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK ((kind = 'ACTIVATION' AND delta = 100 AND trade_id IS NULL AND reverses_entry_id IS NULL) OR
        (kind = 'RATING' AND delta IN (2, 0, -1, -3, -5) AND trade_id IS NOT NULL AND reverses_entry_id IS NULL) OR
        (kind = 'NO_RATING' AND delta = 1 AND trade_id IS NOT NULL AND reverses_entry_id IS NULL) OR
        (kind = 'REVERSAL' AND reverses_entry_id IS NOT NULL))
);
CREATE UNIQUE INDEX one_initial_reputation_per_member ON reputation_entries(member_id) WHERE kind = 'ACTIVATION';
CREATE UNIQUE INDEX one_rating_effect_per_trade ON reputation_entries(trade_id) WHERE kind IN ('RATING', 'NO_RATING');
CREATE TABLE notifications (
    id UUID PRIMARY KEY,
    recipient_id UUID NOT NULL REFERENCES members(id),
    event_key VARCHAR(200) NOT NULL,
    kind VARCHAR(80) NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    read_at TIMESTAMPTZ,
    UNIQUE (recipient_id, event_key)
);
CREATE INDEX listings_seller ON listings(seller_id);
CREATE INDEX revisions_listing ON listing_revisions(listing_id);
CREATE INDEX revision_items_item ON listing_revision_items(item_id);
CREATE INDEX reservations_buyer ON reservations(buyer_id, created_at);
CREATE INDEX reservations_seller ON reservations(seller_id, created_at);
CREATE INDEX messages_conversation ON messages(conversation_id, created_at, id);
CREATE INDEX trades_review_due ON trades(review_due_at) WHERE state = 'AWAITING_CONFIRMATION';
CREATE INDEX trades_rating_due ON trades(rating_due_at) WHERE state = 'COMPLETED';
CREATE INDEX reports_queue ON reports(state, created_at);
CREATE INDEX notifications_inbox ON notifications(recipient_id, created_at, id);

-- Infrastructure receipt, written in the SAME transaction as the domain mutation.
-- Retention/replay payload handling belongs to the implementing service; never cache challenge plaintext here.
CREATE TABLE command_receipts (
    actor_id UUID NOT NULL REFERENCES members(id),
    operation VARCHAR(100) NOT NULL,
    idempotency_key UUID NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    resource_id UUID NOT NULL,
    result_version BIGINT,
    http_status SMALLINT NOT NULL CHECK (http_status BETWEEN 200 AND 299),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (actor_id, operation, idempotency_key)
);
